# Generated by Kconfiglib (https://github.com/ulfalizer/Kconfiglib)

#
# Toolchain configuration
#
CONFIG_TOOLCHAIN_PATH="/opt/kendryte-toolchain/bin"
CONFIG_TOOLCHAIN_PREFIX="riscv64-unknown-elf-"
# end of Toolchain configuration

#
# Components configuration
#

#
# Drivers configuration
#

#
# Audio Speaker
#
CONFIG_ENABLE_SPK=y
CONFIG_SPK_TYPE_ES8374=y
# CONFIG_SPK_TYPE_PT8211 is not set

#
# ES8374 Pin configuration
#
CONFIG_PIN_NUM_ES8374_MCLK=19
CONFIG_PIN_NUM_ES8374_DIN=18
CONFIG_PIN_NUM_ES8374_DOUT=34
CONFIG_PIN_NUM_ES8374_SCLK=35
CONFIG_PIN_NUM_ES8374_WS=33
CONFIG_PIN_NUM_ES8374_I2C_SDA=31
CONFIG_PIN_NUM_ES8374_I2C_SCL=30
# end of ES8374 Pin configuration
# end of Audio Speaker

#
# Camera( Sensor ) configuration
#

#
# !!!DONT MODIFY CAMERA_RESOLUTION!!!
#
CONFIG_ENABLE_CAMERA=y
# CONFIG_CAMERA_OV2640 is not set
# CONFIG_CAMERA_GC0328_SINGLE is not set
CONFIG_CAMERA_GC0328_DUAL=y
CONFIG_CAMERA_RESOLUTION_WIDTH=320
CONFIG_CAMERA_RESOLUTION_HEIGHT=240
# end of Camera( Sensor ) configuration

#
# LCD configuration
#
CONFIG_ENABLE_LCD=y
CONFIG_LCD_TYPE_ST7789=y
# CONFIG_LCD_TYPE_SIPEED is not set

#
# Lcd ( Display ) configuration
#
CONFIG_LCD_WIDTH=320
CONFIG_LCD_HEIGHT=240
CONFIG_LCD_CLK_FREQ_MHZ=15
# end of Lcd ( Display ) configuration

#
# LCD Pin configuration
#
CONFIG_PIN_NUM_LCD_RST=37
CONFIG_PIN_NUM_LCD_DCX=38
CONFIG_PIN_NUM_LCD_WRX=36
CONFIG_PIN_NUM_LCD_SCK=39
# end of LCD Pin configuration

#
# LCD Pin Func configuration
#
CONFIG_GPIOHS_NUM_LCD_DCX=0
CONFIG_GPIOHS_NUM_LCD_RST=1
# end of LCD Pin Func configuration
# end of LCD configuration

#
# RTC configuration
#
CONFIG_ENABLE_RTC=y
CONFIG_RTC_TYPE_GM1302=y
# CONFIG_RTC_TYPE_BM8563 is not set

#
# GM1302 Pin configuration
#
CONFIG_PIN_NUM_RTC_GM1302_RST=11
CONFIG_PIN_NUM_RTC_GM1302_DAT=13
CONFIG_PIN_NUM_RTC_GM1302_CLK=12
# end of GM1302 Pin configuration

#
# GM1302 Pin Func configuration
#
CONFIG_GPIOHS_NUM_RTC_GM1302_RST=17
CONFIG_GPIOHS_NUM_RTC_GM1302_DAT=18
CONFIG_GPIOHS_NUM_RTC_GM1302_CLK=19
# end of GM1302 Pin Func configuration
# end of RTC configuration

#
# SPI TF card configuration
#
# CONFIG_ENABLE_SD_CARD is not set
# end of SPI TF card configuration
# end of Drivers configuration

#
# Kendryte SDK configurations
#
CONFIG_SDK_LOG_LEVEL=5
# end of Kendryte SDK configurations

#
# Third party config
#
# CONFIG_OOFATFS_ENABLE is not set
# end of Third party config

#
# utils config
#

#
# list config
#
CONFIG_LIST_MAX_NUM=1
CONFIG_LIST_NODE_MAX_NUM=32
CONFIG_LIST_ITERATOR_MAX_NUM=2
# end of list config

# CONFIG_ENABLE_CQUEUE is not set
CONFIG_ENABLE_JPEG_DECODE=y
CONFIG_ENABLE_JPEG_ENCODE=y
# end of utils config
# end of Components configuration

#
# Application configuration
#

#
# Peripheral configuration
#

#
# Key configuration
#
CONFIG_ENABLE_KEY=y
CONFIG_PIN_NUM_USER_KEY=24
CONFIG_GPIOHS_NUM_USER_KEY=6
CONFIG_USER_KEY_PRESS_VOL=1
# end of Key configuration

#
# Relay configuration
#
CONFIG_ENABLE_RELAY=y
CONFIG_RELAY_NUM=1

#
# Relay Pin configuration
#
CONFIG_PIN_NUM_RELAY_1=32
# end of Relay Pin configuration

#
# Relay Pin Func configuration
#
CONFIG_GPIOHS_NUM_RELAY_1=7
# end of Relay Pin Func configuration

CONFIG_RELAY_1_OPEN_VOL=1
# end of Relay configuration

#
# Above init in Uart Proto...
#

#
# IR Led configuration
#
CONFIG_ENABLE_IR_LED=y
CONFIG_PIN_NUM_IR_LED=9
CONFIG_GPIOHS_NUM_IR_LED=9
CONFIG_IR_LED_OPEN_VOL=1
# end of IR Led configuration

#
# Flash Led configuration
#
CONFIG_ENABLE_FLASH_LED=y
CONFIG_PIN_NUM_FLASH_LED=10
CONFIG_GPIOHS_NUM_FLASH_LED=10
CONFIG_FLASH_LED_OPEN_VOL=1
# end of Flash Led configuration

#
# RGB Led configuration
#
# CONFIG_ENABLE_RGB_LED is not set
# end of RGB Led configuration

#
# LCD BackLight configuration
#
CONFIG_ENABLE_LCD_BL=y
CONFIG_PIN_NUM_LCD_BL=17
CONFIG_GPIOHS_NUM_LCD_BL=14
CONFIG_LCD_BL_OPEN_VOL=0
# end of LCD BackLight configuration
# end of Peripheral configuration

#
# NetWork
#
# CONFIG_NET_ENABLE is not set
# end of NetWork

#
# Uart Protocol
#
# CONFIG_ENABLE_UART_PROTOCOL is not set
# end of Uart Protocol

#
# Board Type Select
#
# CONFIG_BOARD_TYPE_MF1 is not set
CONFIG_BOARD_TYPE_CLIENT_1=y
# end of Board Type Select

#
# --------------------------------
#
CONFIG_LCD_VERTICAL=y
# CONFIG_LCD_HORIZONTAL is not set
# CONFIG_NOT_MF1_BOARD is not set
# CONFIG_ENABLE_SD_OTA is not set

#
# --------------------------------
#
CONFIG_SHORT_PRESS_FUNCTION_KEY_RECORD_FACE=y
# CONFIG_LONG_PRESS_FUNCTION_KEY_CLEAR_FEATURE is not set
CONFIG_LONG_PRESS_FUNCTION_KEY_RESTORE=y
# end of Application configuration
